name: attendance_dashboard
description: "Attendance Admin Dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  go_router: ^15.1.2
  get_it: ^8.0.3
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  pdf: ^3.11.2
  printing: ^5.13.5
  excel: ^4.0.6
  data_table_2: ^2.5.16
  file_saver: ^0.2.14
  google_fonts: ^6.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
